Aplikacja Bankowa/bank/bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    
]

Aplikacja Bankowa/bank/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
path("", views.home, name="home"),
path("withdraw/", views.withdraw_view, name="withdraw"),
path("transactions/", views.transactions, name='transactions'),
path("deposit/", views.deposit_view, name='deposit'),
path("transfer/", views.transfer_view, name="transfer"),
path('login/', views.login_view, name='login'),
path("register/", views.register, name="register"),
path('logout/', views.logout_view, name='logout'),
path('transaction_success/', views.transaction_success, name='transaction_success'),
]

Aplikacja Bankowa/bank/main/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    date_of_birth = models.DateField()

    def __str__(self):
        return self.user.username

class AccountData(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    account_number = models.CharField(max_length=20, unique=True)
    balance = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.account_number


class Transaction(models.Model):
    TRANSACTION_TYPES = (
        ('TRANSFER', 'Transfer'),
        ('DEPOSIT', 'Deposit'),
        ('WITHDRAW', 'Withdraw'),
    )

    account = models.ForeignKey(AccountData, on_delete=models.CASCADE, related_name='transactions')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    transaction_type = models.CharField(max_length=10, choices=TRANSACTION_TYPES)
    related_account = models.CharField(max_length=20, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.transaction_type} - {self.amount}"



class Transfer(models.Model):
    sender_account = models.ForeignKey(AccountData, on_delete=models.CASCADE, related_name='sender_transfers')
    receiver_account = models.ForeignKey(AccountData, on_delete=models.CASCADE, related_name='receiver_transfers')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Transfer from {self.sender_account} to {self.receiver_account} - {self.amount}"


class Deposit(models.Model):
    transaction = models.OneToOneField(Transaction, on_delete=models.CASCADE, primary_key=True)


class Withdraw(models.Model):
    transaction = models.OneToOneField(Transaction, on_delete=models.CASCADE, primary_key=True)
    

Aplikacja Bankowa/bank/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Customer

class SignUpForm(UserCreationForm):
    address = forms.CharField(max_length=100)
    phone_number = forms.CharField(max_length=20)
    date_of_birth = forms.DateField()

    class Meta:
        model = User
        fields = ('username', 'address', 'phone_number', 'date_of_birth', 'password1', 'password2')

class LoginForm(forms.Form):
    username = forms.CharField(label="username")
    password = forms.CharField(label="password", widget=forms.PasswordInput)

class TransferForm(forms.Form):
    receiver_account_number = forms.CharField(label='Receiver Account Number', max_length=20)
    amount = forms.DecimalField(label='Amount', max_digits=10, decimal_places=2)

class DepositForm(forms.Form):
    amount = forms.DecimalField(label='Amount', max_digits=10, decimal_places=2)

class WithdrawForm(forms.Form):
    amount = forms.DecimalField(label='Amount', max_digits=10, decimal_places=2)

Aplikacja Bankowa/bank/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from .forms import SignUpForm, LoginForm, TransferForm, DepositForm, WithdrawForm
from django.contrib import messages
from django.contrib.auth.models import User  
from .models import Customer, AccountData, Transaction, Deposit, Withdraw
import random

def home(request):
    return render(request, 'main/home.html')

def transactions(request):
    if hasattr(request.user, 'customer'):
        customer = request.user.customer
        account = customer.accountdata_set.first()
        if account:
            transactions = account.transactions.all()  # Pobieramy wszystkie transakcje powiązane z kontem
        else:
            transactions = []
    else:
        transactions = []
        
    return render(request, 'main/transactions.html', {'transactions': transactions})

def transfer_view(request):
    if request.method == 'POST':
        form = TransferForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['amount']
            receiver_account_number = form.cleaned_data['receiver_account_number']
            
            if hasattr(request.user, 'customer'):
                customer = request.user.customer
                # Ensure we use the correct way to get the account
                sender_account = customer.accountdata_set.first()
                
                if sender_account:
                    print("Sender account:", sender_account)  # Sprawdźmy, czy sender_account jest prawidłowo przypisany
                    
                    try:
                        receiver_account = AccountData.objects.get(account_number=receiver_account_number)
                        print("Receiver account:", receiver_account)
                    except AccountData.DoesNotExist:
                        messages.error(request, 'Receiver account does not exist.')
                        return redirect('transfer')
                    
                    if sender_account.balance >= amount:
                        # Utwórz transakcję w bazie danych
                        transaction = Transaction.objects.create(
                            account=sender_account,
                            amount=-amount,
                            transaction_type='TRANSFER',
                            related_account=receiver_account.account_number
                        )
                        # Zaktualizuj saldo konta źródłowego
                        sender_account.balance -= amount
                        sender_account.save()
                        # Zaktualizuj saldo konta docelowego
                        receiver_account.balance += amount
                        receiver_account.save()
                        # Przekieruj użytkownika do strony powiadomienia o udanej transakcji
                        return redirect('transaction_success')
                    else:
                        # Przekieruj użytkownika do strony błędu (brak wystarczających środków)
                        messages.error(request, 'Insufficient funds.')
                        return redirect('transfer')
                else:
                    messages.error(request, 'No bank account assigned to this user.')
                    return redirect('transfer')
            else:
                messages.error(request, 'No customer assigned to this user.')
                return redirect('transfer')
    else:
        form = TransferForm()
    return render(request, 'main/transfer.html', {'form': form})

def withdraw_view(request):
    if request.method == 'POST':
        form = WithdrawForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['amount']
            customer = request.user.customer
            account = customer.accountdata_set.first()

            if account.balance >= amount:
                # Utwórz transakcję wypłaty w bazie danych
                transaction = Transaction.objects.create(
                    account=account,
                    amount=-amount,
                    transaction_type='WITHDRAW'
                )
                # Zaktualizuj saldo konta
                account.balance -= amount
                account.save()

                
                # Przekieruj użytkownika do strony powiadomienia o udanej wypłacie
                return redirect('transaction_success')
            else:
                messages.error(request, 'Insufficient funds.')
                # Przekieruj użytkownika do strony błędu (brak wystarczających środków)
                return redirect('withdraw')
    else:
        form = WithdrawForm()
    return render(request, 'main/withdraw.html', {'form': form})

def deposit_view(request):
    if request.method == 'POST':
        form = DepositForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['amount']
            customer = request.user.customer
            account = customer.accountdata_set.first()  # Uzyskaj pierwsze konto użytkownika
            # Utwórz transakcję depozytu w bazie danych
            transaction = Transaction.objects.create(
                account=account,
                amount=amount,
                transaction_type='DEPOSIT'
            )
            # Zaktualizuj saldo konta
            account.balance += amount
            account.save()
            # Przekieruj użytkownika do strony powiadomienia o udanym depozycie
            return redirect('transaction_success')
    else:
        form = DepositForm()
    return render(request, 'main/deposit.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # Przekieruj użytkownika po zalogowaniu
                return redirect('home')
            else:
                # Obsłuż błąd uwierzytelniania
                error_message = "Invalid username or password."
    else:
        form = LoginForm()
        error_message = None
    return render(request, 'main/login.html', {'form': form, 'error_message': error_message})

def logout_view(request):
    logout(request)
    messages.success(request, "Zostałeś poprawnie wylogowany.")
    print(messages.get_messages(request))
    return redirect('home') # Po wylogowaniu przekierowujemy użytkownika na stronę główną

def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            address = form.cleaned_data['address']
            phone_number = form.cleaned_data['phone_number']
            date_of_birth = form.cleaned_data['date_of_birth']
            
            user = User.objects.create_user(username=username, password=form.cleaned_data['password1'])
            if user is None:
                messages.error(request, 'Failed to create user account.')
                return redirect('register')
            
            print("User created successfully")
            print(f"Username: {user.username}")
            
            customer = Customer.objects.create(user=user, address=address, phone_number=phone_number, date_of_birth=date_of_birth)
            if customer is None:
                user.delete()
                messages.error(request, 'Failed to create customer profile.')
                return redirect('register')
            
            print("Customer profile created successfully")
            print(f"Address: {customer.address}")
            
            account_number = generate_account_number()
            balance = 0
            account_data = AccountData.objects.create(customer=customer, account_number=account_number, balance=balance)
            if account_data is None:
                user.delete()
                customer.delete()
                messages.error(request, 'Failed to create bank account.')
                return redirect('register')
            
            print("Bank account created successfully")
            print(f"Account number: {account_data.account_number}")
            
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'main/register.html', {'form': form})



def generate_account_number():
    return ''.join(random.choices('0123456789', k=20))

def transaction_success(request):
    last_transaction = Transaction.objects.latest('date')
    transaction_number = last_transaction.pk  # Numer transakcji to identyfikator główny (primary key)
    return render(request, 'main/transaction_success.html', {'transaction_number': transaction_number})

Aplikacja Bankowa/bank/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Banking App</title>
  {% load static %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Wklej to w nagłówek swojego pliku HTML -->

  <link rel="stylesheet" href="{% static 'style.css' %}"> <!-- Poprawiłem to, aby odwoływać się do pliku stylów -->
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid justify-content-between">
      <a class="navbar-brand" href="{% url 'home' %}">Banking App</a>
      <div class="navbar-nav">
        {% if request.user.is_authenticated %}
        <ul class="navbar-nav me-auto">
          <li class="nav-item" style="margin-right: 40px;">
            <a class="nav-link" href="{% url 'transactions' %}">Transactions</a> <!-- Dodajemy link do strony transakcji -->
          </li>
          <li class="nav-item" style="margin-right: 40px;">
            <a class="nav-link" href="{% url 'withdraw' %}">Withdraw</a> <!-- Dodajemy link do strony wypłaty -->
          </li>
          <li class="nav-item" style="margin-right: 40px;">
            <a class="nav-link" href="{% url 'deposit' %}">Deposit</a> <!-- Dodajemy link do strony wpłaty -->
          </li>
          <li class="nav-item" style="margin-right: 40px;">
            <a class="nav-link" href="{% url 'transfer' %}">Transfer</a> <!-- Dodajemy link do strony wpłaty -->
          </li>
          <li class="nav-item dropdown" style="margin-right: 30px;">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-person-circle"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><span class="dropdown-item-text">{{ request.user.username }}</span></li>
              {% if request.user.customer.accountdata_set.all %}
                  {% with account_data=request.user.customer.accountdata_set.first %}
                      <li><span class="dropdown-item-text">Balance: ${{ account_data.balance }}</span></li>
                  {% endwith %}
              {% endif %}
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
           </ul>
          
          </li>
        
        </ul>
        {% else %}
        <ul class="navbar-nav me-auto">
          <li class="nav-item" style="margin-right: 40px;">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item" style="margin-right: 40px;">
            <a class="nav-link" href="{% url 'login' %}">Login</a> <!-- Dodajemy link do logowania -->
          </li>
          <li class="nav-item" style="margin-right: 40px;">
            <a class="nav-link" href="{% url 'register' %}">Sign Up</a> <!-- Dodajemy link do rejestracji -->
          </li>
        </ul>
        {% endif %}
        
      </div>
    </div>
  </nav>

  <div class="container mt-5">
    <div class="row">
      <div class="col-md-1">
        <!-- Sidebar -->
      </div>
      <div class="col-md-10"id="zawartosc">
        <!-- Main Content -->
        <main>
        {% block content %}


        {% endblock %}
        </main>
      </div>
      <div class="col-md-1">
        <!-- Sidebar -->
      </div>
    </div>
  </div>
  
  
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h5>Informacje o firmie</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.</p>
        </div>
        <div class="col-md-4">
          <h5>Numer telefonu</h5>
          <p>Telefon: 123-456-789</p>
        </div>
        <div class="col-md-4">
          <h5>Adres</h5>
          <p>ul. Testowa 1<br>00-000 Warszawa</p>
        </div>
      </div>
    </div>
  </footer>
  
  
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

  
  
    
</body>
</html>

Aplikacja Bankowa/bank/main/templates/main/deposit.html
{% extends "main/base.html" %}
{% block content %}
<div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h2>Wpłać środki</h2>
        <form method="post">
          {% csrf_token %}
          <div class="mb-3">
            <label for="amount" class="form-label">Kwota</label>
            <input type="text" class="form-control" id="amount" name="amount">
          </div>
          <button type="submit" class="btn btn-primary">Wpłać</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

Aplikacja Bankowa/bank/main/templates/main/home.html
{% extends "main/base.html" %}

{% block content %}
<div class="bank-promotion">
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-8 offset-md-2 text-center">
        
        {% if request.user.is_authenticated %}
        
          {% if request.user.customer.accountdata_set.all %}
            {% with account_data=request.user.customer.accountdata_set.first %}
            <div class="account-info card shadow p-4 mb-5 bg-white rounded">
              <h2 class="mb-4">Twoje konto bankowe</h2>
                <div class="info">
                <p>Saldo: <span class="balance">${{ account_data.balance }}</span></p>
                <p>Ilość transakcji: <span class="transactions">{{ account_data.transactions.count }}</span></p>
              </div>
            </div>
            {% endwith %}
          {% endif %}
          
        {% else %}
        
        <h1 class="display-4">Dołącz do naszego banku już dziś!</h1>
        <p class="lead">Oferujemy nie tylko bezpieczne i wygodne rozwiązania bankowe, ale także indywidualne podejście do każdego klienta.</p>
        <div class="features mt-4">
          <p>Zapewniamy atrakcyjne oprocentowanie na lokaty oraz szeroki zakres usług online, dzięki którym możesz zarządzać swoimi finansami z dowolnego miejsca na świecie.</p>
          <p>Nasi doświadczeni doradcy finansowi są gotowi odpowiedzieć na Twoje pytania i pomóc w wyborze najlepszych produktów bankowych dostosowanych do Twoich potrzeb.</p>
          <p>W naszym banku stawiamy na innowacje i rozwój. Dążymy do ciągłego udoskonalania naszych usług, aby zapewnić Ci najlepsze doświadczenia bankowe.</p>
          <p>Bezpieczeństwo Twoich środków jest dla nas priorytetem. Wykorzystujemy najnowocześniejsze technologie i procedury zabezpieczające, aby chronić Twoje pieniądze.</p>
          <p>Dołączając do naszego banku, zyskujesz dostęp do ekskluzywnych ofert, promocji i programów lojalnościowych. Dbamy o naszych klientów i doceniamy ich zaufanie.</p>
          <p>Nie zwlekaj dłużej! Dołącz do naszej społeczności i korzystaj z profesjonalnych usług bankowych, które spełnią Twoje oczekiwania.</p>
        </div>
        <a href="{% url 'register' %}" class="btn btn-primary btn-lg mt-3">Dołącz już teraz!</a>
        
        {% endif %}

      </div>
    </div>
  </div>
</div>
{% endblock %}

Aplikacja Bankowa/bank/main/templates/main/login.html
{% extends "main/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="login_view">
    <h1>Login</h1>
    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Login</button>
    </form>
</div>

{% endblock %}

Aplikacja Bankowa/bank/main/templates/main/logout.html
{% extends 'main/base.html' %}




{% block content %}
<div class="Logout">
    <h1>You have been sucessfully logout</h1>
    <button href="{% url 'home' %}">Main Page</button>
</div>
{% endblock %}

Aplikacja Bankowa/bank/main/templates/main/register.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}


{% block content %}
<div class="card mt-5">
  <div class="card-body">
    <h5 class="card-title">Sign Up</h5>
    <form method="post" class="form">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
  </div>
</div>
{% endblock %}

Aplikacja Bankowa/bank/main/templates/main/transaction_success.html
{% extends "main/base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2>Transaction Successful</h2>
            <p>Your transaction was successful. Transaction Number: {{ transaction_number }}</p>
        </div>
    </div>
</div>
{% endblock %}

Aplikacja Bankowa/bank/main/templates/main/transactions.html
{% extends "main/base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <h2>Historia transakcji</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Typ transakcji</th>
                        <th scope="col">Kwota</th>
                        <th scope="col">Data</th>
                    </tr>
                </thead>
                <tbody>
                    {% for transaction in transactions %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ transaction.get_transaction_type_display }}</td>  <!-- Używamy get_transaction_type_display do wyświetlenia przyjaznej nazwy -->
                        <td>{{ transaction.amount }}</td>
                        <td>{{ transaction.date }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4">Brak transakcji do wyświetlenia.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

Aplikacja Bankowa/bank/main/templates/main/transfer.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container mt-5">
    {% if messages %}
    <div class="alert alert-danger" role="alert">
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    <a href="{% url 'transfer' %}" class="btn btn-secondary">Try again</a>
    {% else %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="receiver_account_number" class="form-label">Receiver Account Number</label>
            <input type="text" class="form-control" id="receiver_account_number" name="receiver_account_number">
        </div>
        <div class="mb-3">
            <label for="amount" class="form-label">Amount</label>
            <input type="text" class="form-control" id="amount" name="amount">
        </div>
        <button type="submit" class="btn btn-primary">Transfer</button>
    </form>
    {% endif %}
</div>
{% endblock %}

Aplikacja Bankowa/bank/main/templates/main/withdraw.html
<!-- withdraw.html -->
{% extends "main/base.html" %}
{% block content %}
<div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h2>Withdraw Funds</h2>
        <div class="container mt-5">
          {% if messages %}
          <div class="alert alert-danger" role="alert">
              <ul>
                  {% for message in messages %}
                  <li>{{ message }}</li>
                  {% endfor %}
              </ul>
          </div>
          <a href="{% url 'withdraw' %}" class="btn btn-secondary">Try again</a>
          {% else %}
          <form method="post">
              {% csrf_token %}
              <div class="mb-3">
                  <label for="amount" class="form-label">Amount</label>
                  <input type="text" class="form-control" id="amount" name="amount">
              </div>
              <button type="submit" class="btn btn-primary">Withdraw</button>
          </form>
          {% endif %}
      </div>

{% endblock %}